---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-socket-to-tcp
  namespace: cilium-system
spec:
  selector:
    matchLabels:
      app: cilium-socket-to-tcp
  template:
    metadata:
      labels:
        app: cilium-socket-to-tcp
    spec:
      containers:
      - name: cilium-socket-to-tcp
        image: alpine/socat
        command: 
        - socat
        - TCP-LISTEN:9000,fork
        - unix-connect:/var/run/cilium/cilium.sock
        resources: {}
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: /var/run/cilium
            name: cilium-run
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-socket-to-tcp
  namespace: cilium-system
spec:
  selector:
    app: cilium-socket-to-tcp
  ports:
  - port: 9000
    targetPort: 9000
