before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "next-{{ incpatch .Version }}"

changelog:
  skip: true

release:
  disable: true

dockers:
  - goarch: 386
    use: buildx
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-386"
    build_flag_templates:
      - "--platform=linux/386"
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - goarch: arm
    goarm: 7
    use: buildx
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-arm"
    build_flag_templates:
      - "--platform=linux/arm"
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - goarch: arm64
    use: buildx
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-arm64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-arm64"


  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}-{{ .ShortCommit }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-{{ .ShortCommit }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .ShortCommit }}-arm64"

  - name_template: "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-386"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-amd64"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-arm"
      - "ghcr.io/kang-makes/{{ .ProjectName }}:latest-{{ .ShortCommit }}-arm64"
