name: Image creation and publishing
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
jobs:
  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run: |
          make build OUTPUT_FOLDER=${{ github.sha }}
      - uses: actions/upload-artifact@main
        with:
          name: build-out-${{ github.sha }}
          path: ${{ github.sha }}/*

# Registrysh maybe?
# ################# #
# package:
#   name: Package Docker
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/download-artifact@main
#       with:
#         name: build-out-${{ github.sha }}
#         path: out
#     - name: Package
#       run: |
#         make package

  build-image:
    name: Push to registry
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
          name: build-out-${{ github.sha }}
          path: out
      - name: Preserve permissions
        # https://github.com/actions/download-artifact#permission-loss
        run: |
          chmod 555 out/nodeport-deleter
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          flavour: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.docker-cache
          cache-to: type=local,dest=/tmp/.docker-cache-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
