name: Image creation and publishing
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run: |
          make build OUTPUT_FOLDER=${{ github.sha }}
      - uses: actions/upload-artifact@main
        with:
          name: build-out-${{ github.sha }}
          path: ${{ github.sha }}/*

# Registrysh maybe?
# ################# #
# package:
#   name: Package Docker
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/download-artifact@main
#       with:
#         name: build-out-${{ github.sha }}
#         path: out
#     - name: Package
#       run: |
#         make package

  build-image:
    name: Push to registry
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
          name: build-out-${{ github.sha }}
          path: out

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
